name: wall-app

services:
  mongodb:
    image: mongo:7
    container_name: wall-mongo
    restart: unless-stopped
    ports:
      - "27322:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - wall-mongodata:/data/db
    networks:
      - wall-network

  backend:
    build:
      context: ../backend/be5-wall
      dockerfile: Dockerfile
    container_name: wall-backend
    restart: unless-stopped
    ports:
      - "5004:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/${MONGO_DB}?authSource=admin
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb
    networks:
      - wall-network

  frontend:
    build:
      context: ../frontend/fe5-wall
      dockerfile: Dockerfile
    container_name: wall-frontend
    restart: unless-stopped
    ports:
      - "3314:80"
    depends_on:
      - backend
    networks:
      - wall-network

volumes:
  wall-mongodata:

networks:
  wall-network:
    driver: bridge